FROM nvidia/cuda:12.4.1-devel-ubuntu22.04
RUN apt-get update && apt-get install -y python3 python3-pip python3-dev 
COPY . /app
WORKDIR /app
RUN pip3 install "numba==0.63.1" numpy fastapi uvicorn[standard]
CMD ["uvicorn", "client:app", "--host", "0.0.0.0"]
