FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY . /app
WORKDIR /app

RUN pip3 install --no-cache-dir fastapi "uvicorn[standard]"

CMD ["uvicorn", "aggregator:app", "--host", "0.0.0.0"]
