# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weather.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "weather.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rweather.proto\x12\x07weather"\x1b\n\x0b\x43ityRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t"8\n\x13TemperatureResponse\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x01\x32V\n\x0eWeatherService\x12\x44\n\x0eGetTemperature\x12\x14.weather.CityRequest\x1a\x1c.weather.TemperatureResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "weather_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CITYREQUEST"]._serialized_start = 26
    _globals["_CITYREQUEST"]._serialized_end = 53
    _globals["_TEMPERATURERESPONSE"]._serialized_start = 55
    _globals["_TEMPERATURERESPONSE"]._serialized_end = 111
    _globals["_WEATHERSERVICE"]._serialized_start = 113
    _globals["_WEATHERSERVICE"]._serialized_end = 199
# @@protoc_insertion_point(module_scope)
